[package]
name = "bevy_timewarp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version = "0.12", default_features = false}
itertools = "0.11.0"
thiserror = "1.0.44"